server.port=8085

// rBPj2.lDnavJYY'C
example.base64Secret=MCJ5bG5tRnVSbylmeGNqR0JlWHF3QVd6VXRpZ1pZYUpFU2R2T0NoVlBzTkhyTUxJNmJEa0tUcFEKNDR6TXVCV2NuTHh2bGVpZllYMWRBZGpQbU9MWmRrWjdlOTBIb3dXUFF0eUhqTHk0bjYycXZQam52dWhveEtNYTU3YTlCQkdDN296cXVKSG9kTlc3ZGhwWlJsbDIzN2NyNFpKWk9MY1BHUmg4VSoycW91VVhhU3BaO2FZT1p4cWhzZ2ZNWW5BemF1V1ZuY0hWRXB3THNva0VuRjdZSUc2bVd0QTI5clFmWEp4VUt6NWJpTXpkYjJoSWQ5ZTNvQ2J4MjlNV3JFcTZxRVgxOEwxZG5kUkllbW5SSDZ4NHVEWUFDbG5GYnd1MWgzckE0RXoyVGtCTTUwRThGZWl3elIweA==
example.username=test
example.password=test
