FROM alpine:3.9.5

RUN apk update && apk upgrade && \
    apk add perl && \
    rm -rf /var/cache/apk/* 
WORKDIR /root
# alternaitively, pack in tar and have Docker expand automatically via ADD
COPY Pushgateway /root/Pushgateway

