/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.7.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.thulasizwe.bank.api;

import com.thulasizwe.bank.dto.PaymentRequest;
import com.thulasizwe.bank.dto.PaymentResponse;
import com.thulasizwe.bank.dto.RefundRequest;
import com.thulasizwe.bank.dto.RefundResponse;
import java.util.UUID;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.service.annotation.*;
import org.springframework.web.multipart.MultipartFile;

import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;


@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", comments = "Generator version: 7.7.0")
public interface PaymentClientApi {

    /**
     * GET /{paymentId}
     *
     * @param paymentId  (required)
     * @return Success (status code 200)
     */
    @HttpExchange(
        method = "GET",
        value = "/{paymentId}",
        accept = { "application/json" }
    )
    ResponseEntity<PaymentResponse> getPaymentStatus(
         @PathVariable("paymentId") UUID paymentId
    );


    /**
     * POST /
     *
     * @param paymentRequest  (required)
     * @return Payment initiated (status code 201)
     */
    @HttpExchange(
        method = "POST",
        value = "/",
        accept = { "application/json" },
        contentType = "application/json"
    )
    ResponseEntity<PaymentResponse> initiatePayment(
         @RequestBody PaymentRequest paymentRequest
    );


    /**
     * POST /{paymentId}/refund
     *
     * @param paymentId  (required)
     * @param refundRequest  (required)
     * @return Refund processed (status code 200)
     */
    @HttpExchange(
        method = "POST",
        value = "/{paymentId}/refund",
        accept = { "application/json" },
        contentType = "application/json"
    )
    ResponseEntity<RefundResponse> refundPayment(
         @PathVariable("paymentId") UUID paymentId,
         @RequestBody RefundRequest refundRequest
    );

}
