spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
spring.kafka.consumer.group-id=${KAFKA_CONSUMER_GROUP_ID:demo-group}
app.kafka.topic=demo-topic
app.kafka.group.id=demo-group3
