version: '3.5'

services:
  grafana:
    image: grafana/grafana:10.4.13
    ports:
      - 3000:3000
    environment:
      - GF_SERVER_HTTP_ADDR=0.0.0.0
    networks:
      - myapp
  app:
    build:
      context: app
      dockerfile: Dockerfile
    container_name: jsongrafanadatasources
    ports:
      - 8181:80
    volumes: []
      # NOTE: should be an array
      #   - $PWD/data:/home/data
    restart: always
    networks:
      - myapp
networks:
  myapp:
    driver: bridge
