FROM node:22-bookworm
RUN apt-get update \
 && apt-cache search openjdk-17-jdk  \
 && apt-get install -qqy maven openjdk-17-jdk

WORKDIR /app
COPY pom.xml /app/
RUN mvn dependency:go-offline -q
COPY . .

RUN node --version
RUN npm --version
RUN mvn --version

RUN mvn -Preact clean package


