version: '3.2'

services:
  apm-server:
    restart: unless-stopped
    build: apm-server
    container_name: apm-server
    cap_add: [ "CHOWN", "DAC_OVERRIDE", "SETGID", "SETUID" ]
    cap_drop: [ "ALL" ]
    ports:
      - "8200:8200"
    healthcheck:
      interval: 10s
      retries: 12
      test: curl --write-out 'HTTP %{http_code}' --fail --silent --output /dev/null http://localhost:8200/

    networks:
      - elastic
  app:
    restart: unless-stopped
    build: app
    container_name: app
    environment:
      - MONITOR=true
    ports:
      - "6000:6000"
    healthcheck:
      interval: 10s
      retries: 12
      test: curl --write-out 'HTTP %{http_code}' --fail --silent --output /dev/null http://localhost:6000/
    depends_on:
      - apm-server
    networks:
      - elastic
networks:
  elastic:
