FROM nginx-custom-build

ENV UID=1000
# remove default configuration
RUN rm -f /etc/nginx/conf.d/default.conf
# TODO:
ARG USER_NAME=myuser
ARG GROUP_NAME=myuser
USER $USER_NAME

EXPOSE 8080
COPY ./app.conf.nonroot /etc/nginx/conf.d/default.conf

CMD ["nginx", "-g", "daemon off;"]
