FROM centos:7

RUN yum install -y vim wget

# install yum repo
RUN rpm --import http://packages.gopivotal.com/pub/rpm/rhel7/app-suite/RPM-GPG-KEY-PIVOTAL-APP-SUITE-EL7
RUN yum-config-manager --add-repo http://packages.pivotal.io/pub/rpm/rhel7/app-suite/x86_64

# install tcserver
RUN yum install -y pivotal-tc-server-standard-3.2.1-RELEASE

# optionally add ojdbc6 and ojdbc7 to tomcat/lib directories
# ADD lib/ojdbc*.jar /tmp/
# RUN find /opt/pivotal/pivotal-tc-server-standard/tomcat-*.RELEASE -type d -name 'lib' -exec cp /tmp/ojdbc7*.jar {} \;

# install java, set JAVA_HOME
RUN yum install -q -y java-1.8.0-openjdk-devel
ENV JAVA_HOME /usr/lib/jvm/jre

# if /etc/alternatives/jre is broken for some reason create the link ourselves
# RUN cd $(/usr/bin/dirname $(/usr/bin/readlink /etc/alternatives/java)) && cd .. && ln -fs $(pwd) /opt/java && readlink /opt/java
# ENV JAVA_HOME /opt/java
# alternatively
# RUN ln -fs $(dirname $(dirname $(/usr/bin/readlink /etc/alternatives/java))) /opt/java && readlink /opt/java

# alternatively download Oracle JDK
# RUN wget -nv --no-cookies --no-check-certificate --header "Cookie: oraclelicense=accept-securebackup-cookie" "http://download.oracle.com/otn-pub/java/jdk/$JAVA_VERSION-$BUILD_VERSION/jdk-$JAVA_VERSION-linux-x64.rpm" -O /tmp/jdk-8-linux-x64.rpm

# RUN wget -nv --no-cookies --no-check-certificate --header "Cookie: gpw_e24=http%3A%2F%2Fwww.oracle.com%2F; oraclelicense=accept-securebackup-cookie" "http://download.oracle.com/otn-pub/java/jdk/8u111-b14/jdk-8u111-linux-x64.rpm"
# RUN yum -y localinstall jdk-8u111-linux-x64.rpm
# RUN rm jdk-*.rpm
# install tcserver instance (01)
RUN mkdir -p /web/tcserver
RUN /opt/pivotal/pivotal-tc-server-standard/tcruntime-instance.sh create -i /web/tcserver 01

# add default manager.war
ADD webapps/manager.war /web/tcserver/01/webapps

EXPOSE 6969 8080 8443

# start the tcserver instance
# and keep the container alive (PID=1) even if need to recycle tc server
CMD /web/tcserver/01/bin/tcruntime-ctl.sh start /web/tcserver/01 && tail -f /web/tcserver/01/logs/catalina.out
