# NOTE: switch to jre-alpine3.9 to allow JDBC and other domain content-specific probes
FROM alpine:3.9
ADD wait_for.sh wait_for.sh
ENTRYPOINT ["sh", "/wait_for.sh", "--host=${SERVICE_HOST}" , "--port=${SERVICE_	PORT}", "--timeout=${TIMEOUT}"]
