# NOTE: switch to jre-alpine3.9 to allow JDBC and other domain content-specific probes
FROM alpine:3.9
# see also https://github.com/Docker-Hub-frolvlad/docker-alpine-bash
RUN apk add --no-cache bash gawk sed grep bc coreutils
ADD wait_for_it.sh wait_for_it.sh
