version: "3.5"

services:
  mcp-server:
    build: ./app1
    container_name: mcp-server
    ports:
      - "9000:9000"
    environment:
      - MCP_BIND=0.0.0.0
      - MCP_PORT=9000
    networks:
      - mcp
        #healthcheck:
        #test: ["CMD", "curl", "-f", "http://localhost:9000/health"]
        #interval: 2s
        #retries: 10
    healthcheck:
      test: ["CMD", "python", "-c", "import socket; s=socket.create_connection(('localhost',9000),2); s.close()"]
      interval: 5s
      timeout: 3s
      retries: 3  
  mcp-client:
    build: ./app2
    container_name: mcp-client
    depends_on:
      - mcp-server
    environment:
      - MCP_HOST=mcp-server
      - MCP_PORT=9000
    restart: "on-failure"    
    # WARNING: the:re is no max_retries or max_restarts - workarounds possible 
    networks:
      - mcp
networks:
  mcp:
