version: "3.5"

services:
  mcp-server:
    build: ./app1
    container_name: mcp-server
    ports:
      - "9000:9000"
    networks:
      - mcp

  mcp-client:
    build: ./app2
    container_name: mcp-client
    depends_on:
      - mcp-server
    environment:
      - MCP_HOST=mcp-server
    networks:
      - mcp
networks:
  mcp:
