version: '3.2'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.react_runtime
    container_name: react_runtime
    ports:
      - "3000:3000"
    depends_on:
      - tusd

  tusd:
    image: tusproject/tusd:v2.9.1
    container_name: tusd_server
    ports:
      - "8080:8080"
    command: >
      -host 0.0.0.0
      -port 8080
      -upload-dir /data
    volumes:
      - /c/Users/$USERNAME/Documents/tus_data:/data

# volumes:
#  tus_data:
