package net.sf.JRecord.cbl2json.zTest.cbl2json.schema;

import static org.junit.Assert.*;

import java.io.IOException;
import java.io.StringWriter;

import org.junit.Test;

import net.sf.JRecord.Common.IFileStructureConstants;
import net.sf.JRecord.External.CopybookLoader;
import net.sf.JRecord.Option.IReformatFieldNames;
import net.sf.JRecord.cbl2json.zTest.json2cbl.Cbl2JsonCode;
import net.sf.cobolToJson.Cobol2Json;
import net.sf.cobolToJson.def.ICobol2Json;

public class TstAmsPoGroupSchemaGen {

	private String STANDARD_AMS_PO_SCHEMA = "{\n"
			+ "  \"$schema\" : \"http://json-schema.org/draft-06/schema#\",\n"
			+ "  \"type\" : \"object\",\n"
			+ "  \"properties\" : {\n"
			+ "    \"amsPoDownloadGroup2\" : {\n"
			+ "      \"type\" : \"array\",\n"
			+ "      \"items\" : {\n"
			+ "        \"type\" : \"object\",\n"
			+ "        \"properties\" : {\n"
			+ "          \"PO_Record\" : {\n"
			+ "            \"type\" : \"object\",\n"
			+ "            \"properties\" : {\n"
			+ "              \"Record_Type\" : {\n"
			+ "                \"type\" : \"string\"\n"
			+ "              },\n"
			+ "              \"Sequence_Number\" : {\n"
			+ "                \"type\" : \"number\"\n"
			+ "              },\n"
			+ "              \"Vendor_PO_Details\" : {\n"
			+ "                \"type\" : \"object\",\n"
			+ "                \"properties\" : {\n"
			+ "                  \"Vendor\" : {\n"
			+ "                    \"type\" : \"integer\"\n"
			+ "                  },\n"
			+ "                  \"PO_Details\" : {\n"
			+ "                    \"type\" : \"object\",\n"
			+ "                    \"properties\" : {\n"
			+ "                      \"PO\" : {\n"
			+ "                        \"type\" : \"integer\"\n"
			+ "                      },\n"
			+ "                      \"Entry_Date\" : {\n"
			+ "                        \"type\" : \"object\",\n"
			+ "                        \"properties\" : {\n"
			+ "                          \"year\" : {\n"
			+ "                            \"type\" : \"integer\"\n"
			+ "                          },\n"
			+ "                          \"month\" : {\n"
			+ "                            \"type\" : \"integer\"\n"
			+ "                          },\n"
			+ "                          \"day_of_month\" : {\n"
			+ "                            \"type\" : \"integer\"\n"
			+ "                          }\n"
			+ "                        }\n"
			+ "                      }\n"
			+ "                    }\n"
			+ "                  }\n"
			+ "                }\n"
			+ "              },\n"
			+ "              \"codes\" : {\n"
			+ "                \"type\" : \"object\",\n"
			+ "                \"properties\" : {\n"
			+ "                  \"beg01_code\" : {\n"
			+ "                    \"type\" : \"string\"\n"
			+ "                  },\n"
			+ "                  \"beg02_code\" : {\n"
			+ "                    \"type\" : \"string\"\n"
			+ "                  }\n"
			+ "                }\n"
			+ "              },\n"
			+ "              \"Department\" : {\n"
			+ "                \"type\" : \"string\"\n"
			+ "              },\n"
			+ "              \"The_Dates\" : {\n"
			+ "                \"type\" : \"object\",\n"
			+ "                \"properties\" : {\n"
			+ "                  \"Expected_Reciept_Date\" : {\n"
			+ "                    \"type\" : \"object\",\n"
			+ "                    \"properties\" : {\n"
			+ "                      \"year\" : {\n"
			+ "                        \"type\" : \"integer\"\n"
			+ "                      },\n"
			+ "                      \"month\" : {\n"
			+ "                        \"type\" : \"integer\"\n"
			+ "                      },\n"
			+ "                      \"day_of_month\" : {\n"
			+ "                        \"type\" : \"integer\"\n"
			+ "                      }\n"
			+ "                    }\n"
			+ "                  },\n"
			+ "                  \"Cancel_by_date\" : {\n"
			+ "                    \"type\" : \"object\",\n"
			+ "                    \"properties\" : {\n"
			+ "                      \"year\" : {\n"
			+ "                        \"type\" : \"integer\"\n"
			+ "                      },\n"
			+ "                      \"month\" : {\n"
			+ "                        \"type\" : \"integer\"\n"
			+ "                      },\n"
			+ "                      \"day_of_month\" : {\n"
			+ "                        \"type\" : \"integer\"\n"
			+ "                      }\n"
			+ "                    }\n"
			+ "                  }\n"
			+ "                }\n"
			+ "              },\n"
			+ "              \"EDI_Type\" : {\n"
			+ "                \"type\" : \"string\"\n"
			+ "              },\n"
			+ "              \"Add_Date\" : {\n"
			+ "                \"type\" : \"object\",\n"
			+ "                \"properties\" : {\n"
			+ "                  \"year\" : {\n"
			+ "                    \"type\" : \"integer\"\n"
			+ "                  },\n"
			+ "                  \"month\" : {\n"
			+ "                    \"type\" : \"integer\"\n"
			+ "                  },\n"
			+ "                  \"day_of_month\" : {\n"
			+ "                    \"type\" : \"integer\"\n"
			+ "                  }\n"
			+ "                }\n"
			+ "              },\n"
			+ "              \"Department_Name\" : {\n"
			+ "                \"type\" : \"string\"\n"
			+ "              },\n"
			+ "              \"Prcoess_Type\" : {\n"
			+ "                \"type\" : \"string\"\n"
			+ "              },\n"
			+ "              \"Order_Type\" : {\n"
			+ "                \"type\" : \"string\"\n"
			+ "              }\n"
			+ "            }\n"
			+ "          },\n"
			+ "          \"Product_Record\" : {\n"
			+ "            \"type\" : \"object\",\n"
			+ "            \"properties\" : {\n"
			+ "              \"Record_Type\" : {\n"
			+ "                \"type\" : \"string\"\n"
			+ "              },\n"
			+ "              \"Pack_details\" : {\n"
			+ "                \"type\" : \"object\",\n"
			+ "                \"properties\" : {\n"
			+ "                  \"Pack_Qty\" : {\n"
			+ "                    \"type\" : \"number\"\n"
			+ "                  },\n"
			+ "                  \"Pack_Cost\" : {\n"
			+ "                    \"type\" : \"number\"\n"
			+ "                  }\n"
			+ "                }\n"
			+ "              },\n"
			+ "              \"Product_details\" : {\n"
			+ "                \"type\" : \"object\",\n"
			+ "                \"properties\" : {\n"
			+ "                  \"APN\" : {\n"
			+ "                    \"type\" : \"integer\"\n"
			+ "                  }\n"
			+ "                }\n"
			+ "              },\n"
			+ "              \"Product\" : {\n"
			+ "                \"type\" : \"integer\"\n"
			+ "              },\n"
			+ "              \"pmg_dtl_tech_key\" : {\n"
			+ "                \"type\" : \"string\"\n"
			+ "              },\n"
			+ "              \"Case_Pack_id\" : {\n"
			+ "                \"type\" : \"string\"\n"
			+ "              },\n"
			+ "              \"Product_Name\" : {\n"
			+ "                \"type\" : \"string\"\n"
			+ "              }\n"
			+ "            }\n"
			+ "          },\n"
			+ "          \"Location_Record\" : {\n"
			+ "            \"type\" : \"object\",\n"
			+ "            \"properties\" : {\n"
			+ "              \"Record_Type\" : {\n"
			+ "                \"type\" : \"string\"\n"
			+ "              },\n"
			+ "              \"location\" : {\n"
			+ "                \"type\" : \"array\",\n"
			+ "                \"items\" : {\n"
			+ "                  \"type\" : \"object\",\n"
			+ "                  \"properties\" : {\n"
			+ "                    \"DC_Number\" : {\n"
			+ "                      \"type\" : \"integer\"\n"
			+ "                    },\n"
			+ "                    \"Pack_Quantity\" : {\n"
			+ "                      \"type\" : \"integer\"\n"
			+ "                    }\n"
			+ "                  }\n"
			+ "                }\n"
			+ "              }\n"
			+ "            }\n"
			+ "          }\n"
			+ "        }\n"
			+ "      }\n"
			+ "    }\n"
			+ "  }\n"
			+ "}";
	
	private String FLATTEN_AMS_PO_SCHEMA = ""
			+ "{\n"
			+ "  \"$schema\" : \"http://json-schema.org/draft-06/schema#\",\n"
			+ "  \"type\" : \"object\",\n"
			+ "  \"properties\" : {\n"
			+ "    \"amsPoDownloadGroup2\" : {\n"
			+ "      \"type\" : \"array\",\n"
			+ "      \"items\" : {\n"
			+ "        \"type\" : \"object\",\n"
			+ "        \"properties\" : {\n"
			+ "          \"PO_Record\" : {\n"
			+ "            \"type\" : \"object\",\n"
			+ "            \"properties\" : {\n"
			+ "              \"Record_Type\" : {\n"
			+ "                \"type\" : \"string\"\n"
			+ "              },\n"
			+ "              \"Sequence_Number\" : {\n"
			+ "                \"type\" : \"number\"\n"
			+ "              },\n"
			+ "              \"Vendor\" : {\n"
			+ "                \"type\" : \"integer\"\n"
			+ "              },\n"
			+ "              \"PO\" : {\n"
			+ "                \"type\" : \"integer\"\n"
			+ "              },\n"
			+ "              \"Entry_Date\" : {\n"
			+ "                \"type\" : \"object\",\n"
			+ "                \"properties\" : {\n"
			+ "                  \"year\" : {\n"
			+ "                    \"type\" : \"integer\"\n"
			+ "                  },\n"
			+ "                  \"month\" : {\n"
			+ "                    \"type\" : \"integer\"\n"
			+ "                  },\n"
			+ "                  \"day_of_month\" : {\n"
			+ "                    \"type\" : \"integer\"\n"
			+ "                  }\n"
			+ "                }\n"
			+ "              },\n"
			+ "              \"beg01_code\" : {\n"
			+ "                \"type\" : \"string\"\n"
			+ "              },\n"
			+ "              \"beg02_code\" : {\n"
			+ "                \"type\" : \"string\"\n"
			+ "              },\n"
			+ "              \"Department\" : {\n"
			+ "                \"type\" : \"string\"\n"
			+ "              },\n"
			+ "              \"Expected_Reciept_Date\" : {\n"
			+ "                \"type\" : \"object\",\n"
			+ "                \"properties\" : {\n"
			+ "                  \"year\" : {\n"
			+ "                    \"type\" : \"integer\"\n"
			+ "                  },\n"
			+ "                  \"month\" : {\n"
			+ "                    \"type\" : \"integer\"\n"
			+ "                  },\n"
			+ "                  \"day_of_month\" : {\n"
			+ "                    \"type\" : \"integer\"\n"
			+ "                  }\n"
			+ "                }\n"
			+ "              },\n"
			+ "              \"Cancel_by_date\" : {\n"
			+ "                \"type\" : \"object\",\n"
			+ "                \"properties\" : {\n"
			+ "                  \"year\" : {\n"
			+ "                    \"type\" : \"integer\"\n"
			+ "                  },\n"
			+ "                  \"month\" : {\n"
			+ "                    \"type\" : \"integer\"\n"
			+ "                  },\n"
			+ "                  \"day_of_month\" : {\n"
			+ "                    \"type\" : \"integer\"\n"
			+ "                  }\n"
			+ "                }\n"
			+ "              },\n"
			+ "              \"EDI_Type\" : {\n"
			+ "                \"type\" : \"string\"\n"
			+ "              },\n"
			+ "              \"Add_Date\" : {\n"
			+ "                \"type\" : \"object\",\n"
			+ "                \"properties\" : {\n"
			+ "                  \"year\" : {\n"
			+ "                    \"type\" : \"integer\"\n"
			+ "                  },\n"
			+ "                  \"month\" : {\n"
			+ "                    \"type\" : \"integer\"\n"
			+ "                  },\n"
			+ "                  \"day_of_month\" : {\n"
			+ "                    \"type\" : \"integer\"\n"
			+ "                  }\n"
			+ "                }\n"
			+ "              },\n"
			+ "              \"Department_Name\" : {\n"
			+ "                \"type\" : \"string\"\n"
			+ "              },\n"
			+ "              \"Prcoess_Type\" : {\n"
			+ "                \"type\" : \"string\"\n"
			+ "              },\n"
			+ "              \"Order_Type\" : {\n"
			+ "                \"type\" : \"string\"\n"
			+ "              }\n"
			+ "            }\n"
			+ "          },\n"
			+ "          \"Product_Record\" : {\n"
			+ "            \"type\" : \"object\",\n"
			+ "            \"properties\" : {\n"
			+ "              \"Record_Type\" : {\n"
			+ "                \"type\" : \"string\"\n"
			+ "              },\n"
			+ "              \"Pack_Qty\" : {\n"
			+ "                \"type\" : \"number\"\n"
			+ "              },\n"
			+ "              \"Pack_Cost\" : {\n"
			+ "                \"type\" : \"number\"\n"
			+ "              },\n"
			+ "              \"APN\" : {\n"
			+ "                \"type\" : \"integer\"\n"
			+ "              },\n"
			+ "              \"Product\" : {\n"
			+ "                \"type\" : \"integer\"\n"
			+ "              },\n"
			+ "              \"pmg_dtl_tech_key\" : {\n"
			+ "                \"type\" : \"string\"\n"
			+ "              },\n"
			+ "              \"Case_Pack_id\" : {\n"
			+ "                \"type\" : \"string\"\n"
			+ "              },\n"
			+ "              \"Product_Name\" : {\n"
			+ "                \"type\" : \"string\"\n"
			+ "              }\n"
			+ "            }\n"
			+ "          },\n"
			+ "          \"Location_Record\" : {\n"
			+ "            \"type\" : \"object\",\n"
			+ "            \"properties\" : {\n"
			+ "              \"Record_Type\" : {\n"
			+ "                \"type\" : \"string\"\n"
			+ "              },\n"
			+ "              \"location\" : {\n"
			+ "                \"type\" : \"array\",\n"
			+ "                \"items\" : {\n"
			+ "                  \"type\" : \"object\",\n"
			+ "                  \"properties\" : {\n"
			+ "                    \"DC_Number\" : {\n"
			+ "                      \"type\" : \"integer\"\n"
			+ "                    },\n"
			+ "                    \"Pack_Quantity\" : {\n"
			+ "                      \"type\" : \"integer\"\n"
			+ "                    }\n"
			+ "                  }\n"
			+ "                }\n"
			+ "              }\n"
			+ "            }\n"
			+ "          }\n"
			+ "        }\n"
			+ "      }\n"
			+ "    }\n"
			+ "  }\n"
			+ "}";

	private String ARRAY_AMS_PO_SCHEMA = ""
			+ "{\n"
			+ "  \"$schema\" : \"http://json-schema.org/draft-06/schema#\",\n"
			+ "  \"type\" : \"array\",\n"
			+ "  \"items\" : {\n"
			+ "    \"type\" : \"object\",\n"
			+ "    \"properties\" : {\n"
			+ "      \"PO_Record\" : {\n"
			+ "        \"type\" : \"object\",\n"
			+ "        \"properties\" : {\n"
			+ "          \"Record_Type\" : {\n"
			+ "            \"type\" : \"string\"\n"
			+ "          },\n"
			+ "          \"Sequence_Number\" : {\n"
			+ "            \"type\" : \"number\"\n"
			+ "          },\n"
			+ "          \"Vendor\" : {\n"
			+ "            \"type\" : \"integer\"\n"
			+ "          },\n"
			+ "          \"PO\" : {\n"
			+ "            \"type\" : \"integer\"\n"
			+ "          },\n"
			+ "          \"Entry_Date\" : {\n"
			+ "            \"type\" : \"object\",\n"
			+ "            \"properties\" : {\n"
			+ "              \"year\" : {\n"
			+ "                \"type\" : \"integer\"\n"
			+ "              },\n"
			+ "              \"month\" : {\n"
			+ "                \"type\" : \"integer\"\n"
			+ "              },\n"
			+ "              \"day_of_month\" : {\n"
			+ "                \"type\" : \"integer\"\n"
			+ "              }\n"
			+ "            }\n"
			+ "          },\n"
			+ "          \"beg01_code\" : {\n"
			+ "            \"type\" : \"string\"\n"
			+ "          },\n"
			+ "          \"beg02_code\" : {\n"
			+ "            \"type\" : \"string\"\n"
			+ "          },\n"
			+ "          \"Department\" : {\n"
			+ "            \"type\" : \"string\"\n"
			+ "          },\n"
			+ "          \"Expected_Reciept_Date\" : {\n"
			+ "            \"type\" : \"object\",\n"
			+ "            \"properties\" : {\n"
			+ "              \"year\" : {\n"
			+ "                \"type\" : \"integer\"\n"
			+ "              },\n"
			+ "              \"month\" : {\n"
			+ "                \"type\" : \"integer\"\n"
			+ "              },\n"
			+ "              \"day_of_month\" : {\n"
			+ "                \"type\" : \"integer\"\n"
			+ "              }\n"
			+ "            }\n"
			+ "          },\n"
			+ "          \"Cancel_by_date\" : {\n"
			+ "            \"type\" : \"object\",\n"
			+ "            \"properties\" : {\n"
			+ "              \"year\" : {\n"
			+ "                \"type\" : \"integer\"\n"
			+ "              },\n"
			+ "              \"month\" : {\n"
			+ "                \"type\" : \"integer\"\n"
			+ "              },\n"
			+ "              \"day_of_month\" : {\n"
			+ "                \"type\" : \"integer\"\n"
			+ "              }\n"
			+ "            }\n"
			+ "          },\n"
			+ "          \"EDI_Type\" : {\n"
			+ "            \"type\" : \"string\"\n"
			+ "          },\n"
			+ "          \"Add_Date\" : {\n"
			+ "            \"type\" : \"object\",\n"
			+ "            \"properties\" : {\n"
			+ "              \"year\" : {\n"
			+ "                \"type\" : \"integer\"\n"
			+ "              },\n"
			+ "              \"month\" : {\n"
			+ "                \"type\" : \"integer\"\n"
			+ "              },\n"
			+ "              \"day_of_month\" : {\n"
			+ "                \"type\" : \"integer\"\n"
			+ "              }\n"
			+ "            }\n"
			+ "          },\n"
			+ "          \"Department_Name\" : {\n"
			+ "            \"type\" : \"string\"\n"
			+ "          },\n"
			+ "          \"Prcoess_Type\" : {\n"
			+ "            \"type\" : \"string\"\n"
			+ "          },\n"
			+ "          \"Order_Type\" : {\n"
			+ "            \"type\" : \"string\"\n"
			+ "          }\n"
			+ "        }\n"
			+ "      },\n"
			+ "      \"Product_Record\" : {\n"
			+ "        \"type\" : \"object\",\n"
			+ "        \"properties\" : {\n"
			+ "          \"Record_Type\" : {\n"
			+ "            \"type\" : \"string\"\n"
			+ "          },\n"
			+ "          \"Pack_Qty\" : {\n"
			+ "            \"type\" : \"number\"\n"
			+ "          },\n"
			+ "          \"Pack_Cost\" : {\n"
			+ "            \"type\" : \"number\"\n"
			+ "          },\n"
			+ "          \"APN\" : {\n"
			+ "            \"type\" : \"integer\"\n"
			+ "          },\n"
			+ "          \"Product\" : {\n"
			+ "            \"type\" : \"integer\"\n"
			+ "          },\n"
			+ "          \"pmg_dtl_tech_key\" : {\n"
			+ "            \"type\" : \"string\"\n"
			+ "          },\n"
			+ "          \"Case_Pack_id\" : {\n"
			+ "            \"type\" : \"string\"\n"
			+ "          },\n"
			+ "          \"Product_Name\" : {\n"
			+ "            \"type\" : \"string\"\n"
			+ "          }\n"
			+ "        }\n"
			+ "      },\n"
			+ "      \"Location_Record\" : {\n"
			+ "        \"type\" : \"object\",\n"
			+ "        \"properties\" : {\n"
			+ "          \"Record_Type\" : {\n"
			+ "            \"type\" : \"string\"\n"
			+ "          },\n"
			+ "          \"location\" : {\n"
			+ "            \"type\" : \"array\",\n"
			+ "            \"items\" : {\n"
			+ "              \"type\" : \"object\",\n"
			+ "              \"properties\" : {\n"
			+ "                \"DC_Number\" : {\n"
			+ "                  \"type\" : \"integer\"\n"
			+ "                },\n"
			+ "                \"Pack_Quantity\" : {\n"
			+ "                  \"type\" : \"integer\"\n"
			+ "                }\n"
			+ "              }\n"
			+ "            }\n"
			+ "          }\n"
			+ "        }\n"
			+ "      }\n"
			+ "    }\n"
			+ "  }\n"
			+ "}";

	@Test
	public void testStandard() throws IOException {
		ICobol2Json jsnBldr = getCobol2JsonNormalBuilder();
		StringWriter schemaWriter = new StringWriter();
		
		jsnBldr.jsonSchemaForCobol2json(schemaWriter);
		
		//System.out.println(schemaWriter.toString());
		assertEquals(STANDARD_AMS_PO_SCHEMA, schemaWriter.toString()); 
	}
	
	@Test
	public void testFlatten() throws IOException {
		ICobol2Json jsnBldr = getCobol2JsonNormalBuilder()	.setFlattenStructure(true);
		StringWriter schemaWriter = new StringWriter();
		
		jsnBldr.jsonSchemaForCobol2json(schemaWriter);
		
		System.out.println(schemaWriter.toString());
		assertEquals(FLATTEN_AMS_PO_SCHEMA, schemaWriter.toString()); 
	}

	@Test
	public void testArray() throws IOException {
		//System.out.println(ARRAY_AMS_PO_SCHEMA);
		ICobol2Json jsnBldr = getCobol2JsonNormalBuilder()
				.setFlattenStructure(true)
				.setNameMainArray(false);
		StringWriter schemaWriter = new StringWriter();
		
		//jsnBldr.writeSampleCobol2json("/Volumes/BruceMacHD/Temp/amsPoDownload_sample.json");
		
		try {
			jsnBldr.jsonSchemaForCobol2json(schemaWriter);
		} catch (IOException e) {
			schemaWriter.close();
			e.printStackTrace();
		}
		
		//System.out.println(schemaWriter.toString());
		
		assertEquals(ARRAY_AMS_PO_SCHEMA, schemaWriter.toString()); 
		 
	}
	
	
	private ICobol2Json getCobol2JsonNormalBuilder() {
		 	
		return Cobol2Json.newCobol2Json(Cbl2JsonCode.getFullName("cobol/amsPoDownloadGroup2.cbl"))
					  .setFileOrganization(IFileStructureConstants.IO_BIN_TEXT)
	//				  .setPrettyPrint(true)
					  .setSplitCopybook(CopybookLoader.SPLIT_01_LEVEL)
					  .setTagFormat(IReformatFieldNames.RO_UNDERSCORE);

	}
}
