# FROM gradle:5.4.1-jdk8-alpine
# NOTE: gradle image has no root user
FROM maven:3.6.1-jdk-8-alpine
WORKDIR /work
# NOTE: alternatively can share build project src and target with Docker container

COPY pom.xml /work/
RUN mvn dependency:go-offline -ntp -B
ADD src /work/src
CMD ["mvn", "-Pjdk8", "test"]
