<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<definitions xmlns = "http://schemas.xmlsoap.org/wsdl/" targetNamespace="http://springsoapwshellow.guillaumebraibant/soap" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:tns="http://springsoapwshellow.guillaumebraibant/soap" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:http="http://schemas.xmlsoap.org/wsdl/http/">
    <!-- Import custom XML types from .xsd files -->

    <!-- Import the type from the full-name.xsd file that is put aside the wsdl in the src/main/resources folder -->
    <types>
        <xs:schema>
            <xs:import schemaLocation="full-name.xsd" namespace="http://springsoapwshellow.guillaumebraibant/soap"/>
        </xs:schema>
    </types>

    <!-- Define the messages exchanged -->

    <!-- Define the input message : the full name of the user -->    
    <message name="sayHelloInput">
        <part name="username" type="tns:fullName"/>
    </message>
    
    <!-- Define the output message : A sentence saying : "Hello <fullUsername> from <HOSTNAME>" -->
    <message name="sayHelloOutput">
        <part name="response" type="xs:string"/>
    </message>
    
    <!-- Define the operations available through the webservice -->
    
    <!-- Define the interface sayHelloInterface that will have one method named sayHello -->
    <portType name="sayHelloInterface">
        <documentation>This interface exposes several method that compute a greeting message based on the provided username</documentation>
        <operation name="sayHello">
            <documentation>This operation takes in a parameter a user name and return a greeting message</documentation>
            <!-- The method sayHello uses the two messages defined in the message elements -->
            <input name="request" message="tns:sayHelloInput" />
            <output name="response" message="tns:sayHelloOutput" />
        </operation>
    </portType>
    
    <!-- Define how to interact with the webservice -->

    <!-- Define the protocol used for the sayHello service : SOAP on HTTP with an XML document put in the soap:body -->
    <binding name="sayHelloSoapHttpBinding" type="tns:sayHelloInterface">
        <soap12:binding transport="http://schemas.xmlsoap.org/soap/http" style="document" />
        <operation name="sayHello">
            <input>
                <soap:body use="literal"/>
            </input>
            <output>
                <soap:body use="literal"/>
            </output>
        </operation>
    </binding>
    
    <!-- Define where the webservice will be located-->

    <!-- The services will be located at http://localhost:8080/services/sayHello -->
    <service name="sayHelloService">
        <port name="sayHelloInterface" binding="tns:sayHelloSoapHttpBinding">
            <!-- Do not mind about it, the framework will rewrite it accordingly -->
            <soap:address location="http://localhost:8080/services/sayhello" />
        </port>
    </service>
</definitions>