FROM alpine:3.9.5
# based on: https://github.com/mvertes/docker-alpine-mongo
RUN apk add --no-cache mongodb

VOLUME /data/db
EXPOSE 27017 28017

WORKDIR /root
COPY run.sh ./
# NOTE: shell script are Windows Line endings sensitive
RUN sed -i 's|\r||g' run.sh
ENTRYPOINT ["./run.sh"]
CMD [ "mongod", "--bind_ip", "0.0.0.0" ]
