FROM alpine:3.9.5
# based on: https://github.com/mvertes/docker-alpine-mongo
RUN apk add --no-cache mongodb

VOLUME /data/db
EXPOSE 27017 28017

# NOTE: Windows Line endings sensitive
COPY run.sh /root
ENTRYPOINT [ "/root/run.sh" ]
CMD [ "mongod", "--bind_ip", "0.0.0.0" ]
