# FROM node:8.12-alpine
FROM node:16.12.0-alpine3.11

RUN apk update && apk add --update --no-cache docker-cli python3 python g++ make 


WORKDIR /src
ADD ./backend /src/backend/
ADD ./client /src/client/
ADD ./app.js /src/
RUN cd backend && npm install --silent || echo 'Done.'
# TODO: properly ignore npm warning
# New minor version of npm available! 8.1.0 -> 8.17.0
EXPOSE 3230
CMD ["node", "/src/app.js"]
