FROM node:8.12-alpine
RUN apk update && apk add --update --no-cache docker python
# NOTE: 
# on node:8.12 alpine
# ERROR: unsatisfiable constraints:
#  docker-cli (missing):


WORKDIR /src
ADD ./backend /src/
ADD ./client /src/
ADD ./app.js /src/
RUN cd backend && npm install --silent
EXPOSE 3230
CMD ["node", "/src/app.js"]
