server.port: 8080

spring.servlet.multipart.enabled = true
# threshold after which files are written to disk.
spring.servlet.multipart.file-size-threshold = 10MB
# max file size defines the maximum size allowed for a single uploaded file. 
# When application attempt file exceeds, 
# backend throw a MaxUploadSizeExceededException
spring.servlet.multipart.max-file-size = 200MB
# max request size limits the sum total of all parts in the request, including: 
# All uploaded files.
# Any additional form fields or parameters included in the request 
spring.servlet.multipart.max-request-size = 1024MB

# file storage
# NOTE: cannot use property names file.upload-dir-windows
# NOTE: the upload directory must be created explicitly
file.uploaddir-windows: c:/temp/upload
file.uploaddir-linux: /tmp/upload
debug: true
# NOTE: suppress verbose Spring Boot CONDITIONS EVALUATION REPORT
logging.level.org.springframework.boot.autoconfigure=INFO
logging.level.org.springframework=INFO
