global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'json_exporter'
    metrics_path: /probe
    file_sd_configs:
      - files:
          - /etc/prometheus/dynamic_targets.json
        refresh_interval: 15s
    relabel_configs:
      - source_labels: [target]
        target_label: __param_target
      - source_labels: [module]
        target_label: __param_module
      - target_label: __address__
        replacement: exporter:7979
      - source_labels: [target]
        target_label: instance
        

