version: '3'
services:
  poi:
    restart: always
    image: t5750/poi
    container_name: poi
    hostname: poi
    ports:
      - 8080:8080
    environment:
      TZ: Asia/Shanghai
    volumes:
      - /etc/localtime:/etc/localtime:ro
