server.servlet.context-parameters.defaultHtmlEscape=true

mail.store.host=localhost
mail.store.port=3143
mail.store.protocol=imap

spring.mail.default-encoding=UTF-8
spring.mail.host=localhost
spring.mail.username=foo@example.com
spring.mail.password=password
spring.mail.port=3025
spring.mail.protocol=smtp
spring.mail.test-connection=false
spring.mail.properties.mail.debug=true
spring.mail.properties.mail.smtp.debug=true
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls=true

mail.receive.schedule.interval.milliseconds = 3000