FROM python:3.9-alpine

# update apk repo
# install chromedriver
RUN echo "http://dl-4.alpinelinux.org/alpine/v3.14/main" >> /etc/apk/repositories \ 
     && echo "http://dl-4.alpinelinux.org/alpine/v3.14/community" >> /etc/apk/repositories \
    && apk update \
    && apk upgrade -U -a \
    && apk add --no-cache  chromium chromium-chromedriver  \
    && rm -rf /var/cache/* \
    && mkdir /var/cache/apk

# upgrade pip
RUN pip install --upgrade pip

# install selenium and additional packages
RUN pip install bs4 selenium
