# Dropwizard config
server:
  allowedMethods: ["GET"]
  adminConnectors: []
  applicationConnectors:
    - type: http
      port: 3460
      maxRequestHeaderSize: 100KiB
  rootPath: /api
  maxThreads: 1024

logging:
  type: external

# Delegate Config
