FROM alpine:3.9.5
ENV RUNNER_VERSION=16.11.0

RUN apk --no-cache add ca-certificates curl \
  && curl -L --output /usr/local/bin/gitlab-runner \
     https://gitlab-runner-downloads.s3.amazonaws.com/v${RUNNER_VERSION}/binaries/gitlab-runner-linux-amd64 \
  && chmod +x /usr/local/bin/gitlab-runner

ENTRYPOINT ["/usr/local/bin/gitlab-runner"]
