---
 
 - name: setup
   setup:
   
 - name: memory check
   vars:
     expected_mem_mb: '{{ ( expected_mem_gb | int ) * 1024 }}'
   assert: 
     that:
       - ansible_memtotal_mb >= (expected_mem_mb | int)
     msg: 'memory is low: found {{ ansible_memtotal_mb }} need {{ expected_mem_mb }}'

  
 - name: facts check
   debug:
     # NOT OK to use single qotes exclusively
     msg: "{{ vars['ansible_facts'] }}"
