-- top20 procedure
DROP PROCEDURE IF EXISTS `top20`;

DELIMITER $$
CREATE DEFINER=`root`@`%` PROCEDURE `top20`()
BEGIN
TRUNCATE TOP20;
INSERT INTO TOP20
SELECT
    BOOK_ID,
    sum(VOTE)/count(*) AS AVERAGE ,
    (SELECT (count(*)/count(*)+100)*(sum(VOTE)/count(*)) + (( 100/(count(*)+100) )*(select sum(VOTE)/count(*) from VOTE)) ) AS WR
FROM VOTE
GROUP BY BOOK_ID  HAVING COUNT(*) > 100
ORDER BY `WR`  DESC LIMIT 20;

END$$
DELIMITER ;

DROP EVENT IF EXISTS `updateTop20`;
CREATE
DEFINER=`root`@`%` EVENT `updateTop20` ON SCHEDULE EVERY 12 HOUR STARTS '2021-06-23 00:00:00' ON COMPLETION NOT PRESERVE ENABLE DO CALL TOP20()
