version: "3.5"

services:
  act:
    image: alpine:3.18
    working_dir: /workspace

    volumes:
      # current project
      - $(pwd):/workspace

      # Docker-outside-of-Docker io socket - Linux host assumed
      - /var/run/docker.sock:/var/run/docker.sock

      # installer script (development version)
      - $(pwd)/tarinstall.sh:/usr/local/bin/tarinstall.sh:ro

    environment:
      VERSION: latest

    entrypoint:
      - /bin/sh
      - -c
      - |
        set -e

        apk add --no-cache curl wget git ca-certificates

        RELEASE=https://github.com/nektos/act/releases

        VERSION=${VERSION:-latest}

        if [ "$$VERSION" = "latest" ]; then
            VERSION=$$(...)
        fi

        chmod +x /usr/local/bin/tarinstall.sh

        /usr/local/bin/tarinstall.sh \
            -v \
            -x act \
            "$$RELEASE/download/v$${VERSION#v}/act_Linux_x86_64.tar.gz"

        exec act "$$@"
      --


