version : '3'

services:
  zipkin:
    image: openzipkin/zipkin
    ports:
      - 9411:9411
    networks:
      - example
  
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "6831:6831/udp"
      - "16686:16686"
    networks:
      - example

  hotrod:
    image: jaegertracing/example-hotrod:latest
    ports:
      - "8080:8080"
    command: [ "all" ]
    environment:
      - JAEGER_AGENT_HOST=jaeger
      - JAEGER_AGENT_PORT=6831
    networks:
      - example
    depends_on:
      - jaeger

networks:
  example:
    
volumes:
  log_location:
