FROM alpine:3.9.5
RUN apk update && apk add rrdtool rrdtool-dev 
WORKDIR /
COPY mysql_client /
COPY config.yaml / 
COPY example /
WORKDIR /

RUN echo "#!/bin/sh" | tee /tmp/all_arguments.sh; \
    echo "VAR=\"\$@\"; /example \$VAR" | tee -a /tmp/all_arguments.sh; \
    chmod +x /tmp/all_arguments.sh
ENTRYPOINT [ "/tmp/all_arguments.sh" ]
