FROM builder-centos

ENV GOOS=linux
ENV GOARCH=amd64
# ENV CGO_ENABLED=0
ENV GO111MODULE=on

WORKDIR /build
COPY . .
RUN GOOS=$GOOS GOARCH=$GOARCH go build -ldflags "-s -w" -o example rrdserver.go



