rem * -------------------------------------------------------------------
rem *
rem *  Purpose:  Convert a cobol Data file using Cobol Copybook to Json
rem *   Author:  RecordEditor~CodeGen
rem * Language:  Windows bat
rem * Packages   JRecord    (https://sourceforge.net/projects/jrecord/) holds Cobol2Json jar
rem *            Cb2Xml     (https://sourceforge.net/projects/cb2xml/)
rem *        
rem * *------------- Keep this notice in your final code ---------------
rem * *   This code was generated by JRecord projects CodeGen program
rem * *            on the: 21 Jun 2016 18:53:34 
rem * *     from Copybook: DTAR020.cbl
rem * *           Dialect: FMT_MAINFRAME
rem * *          Template: batCbl2Json
rem * *             Split: SPLIT_NONE   
rem * * File Organization: IO_FIXED_LENGTH   
rem * *              Font: cp037
rem * *   
rem * *    CodeGen Author: Bruce Martin
rem * *-----------------------------------------------------------------
rem *
rem *  This script uses the Cobol2Json from the JRecord Package:
rem *  https://sourceforge.net/projects/jrecord/
rem *
rem * -------------------------------------------------------------------

java -jar ../lib/Cobol2Json.jar -cobol cobol/DTAR020.cbl ^
                                    -fileOrganisation FixedWidth ^
                                    -font cp037 ^
                                -input  in/DTAR020.bin   ^
                                -output out/DTAR020.bin1.json
pause
