version: '3'

services:
  test:
    container_name: test
    build:
      context: .
      dockerfile: ./Dockerfile
    image: test:1.0.0
    restart: always
    volumes:
      - ./:/code/
    networks:
      - test

networks:
  test:
    driver: bridge
