server.name: kibana
server.host: 0.0.0.0
elasticsearch.hosts: [ "http://elasticsearch:9200" ]
# monitoring.ui.container.elasticsearch.enabled: true
#Error: \"monitoring.ui.container.elasticsearch.enabled\" setting was not applied. Check for spelling errors and ensure that expected plugins are installed.
xpack.security.enabled: true

# elasticsearch.username: elastic
# elasticsearch.password: elasticpassword
