services:   
  rabbitmq:
    image: rabbitmq:latest
    container_name: rabbitmq 
    hostname: rabbitmq
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_DEFAULT_VHOST: /
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq￼    
    ports:
      - "5672:5672"
      - "15672:15672"
