FROM golang:alpine3.9
ADD . /app
WORKDIR /app

ENV GOOS=linux
ENV GOARCH=amd64
ENV CGO_ENABLED=0
COPY example1.go example2.go /app/
RUN GOOS=$GOOS GOARCH=$GOARCH go build -ldflags "-s -w" -o example1 example1.go
RUN GOOS=$GOOS GOARCH=$GOARCH go build -ldflags "-s -w" -o example2 example2.go
