FROM golang:alpine3.9
ADD . /app
# NOTE: repeated below with explicit copy
WORKDIR /app

ENV GOOS=linux
ENV GOARCH=amd64
ENV CGO_ENABLED=0
COPY example4.go test.json /app/
RUN GOOS=$GOOS GOARCH=$GOARCH go build -ldflags "-s -w" -o example4 example4.go
RUN go run example4.go || exit 0


