version: '3'

services:
  app:
    image: app
    container_name: app
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${HTTP_PORT}:${HTTP_PORT}
    env_file:
      - .env
