flowchart LR

    W[W]

    subgraph L[Linux Developer machine]
        direction LR

        subgraph Docker[Container cluster]
            direction LR
            C["🌐Chrome C"]
            F[F]
            B[B]
            D[D]
        end
    end

    W --> L

    C -->|Web| F

    F -->|REST| B
    B -.->|WebSocket| F
    B -->|JDBC| D

    C -.->|Logs| L


