server {
  listen 80;
  server_name _;
  root /usr/share/nginx/html;
  index index.html;

  location / {
    try_files $uri $uri/ /index.html;
  }
  # deny access to .env
  location ~/\. {
    deny all;
  }
  client_max_body_size 100m;
}
