version: '3.5'

services:
  app:
    restart: unless-stopped
    build: app
    ports:
      - "8080:80"

  exporter:
    build: exporter
    depends_on: 
      - app
      
    ports:
      - "7979:7979"

#  exporter_patched:
#    build: exporter_patched
#      depends_on: app

  prometheus:
    build: prometheus
    depends_on: 
      - exporter 
    ports:
      - "9090:9090"

