version: '3.5'

services:
  app:
#    restart: unless-stopped
    build: app
    ports:
      - "8080:80"
    networks:
      - myapp

  exporter:
    build: exporter
    depends_on: 
      - app
      
    ports:
      - "7979:7979"
    networks:
      - myapp

  prometheus:
    build: prometheus
    depends_on: 
      - exporter 
    ports:
      - "9090:9090"
    networks:
      - myapp

  grafana:
    container_name: grafana
    build: grafana
    ports:
      - 3000:3000
    working_dir: '/scripts'
    restart: always
    depends_on: 
      - prometheus
    tty: false
    networks:
      - myapp
    extra_hosts:
      - "host.docker.internal:192.168.99.100"
networks:
  myapp:
    driver: bridge
