# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = '2'
basedir = ENV.fetch('USERPROFILE', '')
basedir = ENV.fetch('HOME', '') if basedir == ''

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  # set to false, if you do NOT want to check the correct VirtualBox Guest Additions version when booting this box
  if defined?(VagrantVbguest::Middleware)
    config.vbguest.auto_update = false
  end
  # https://app.vagrantup.com/stevesimpson/boxes/elasticsearch/versions/2.0.0
  config.vm.box = 'stevesimpson/elasticsearch'
  config_vm_box_name = 'elastic.box'
  config.vm.box_url = "file://#{basedir}/Downloads/#{config_vm_box_name}"

  config.vm.network :forwarded_port, guest: 5601, host: 5601
  config.vm.network :forwarded_port, guest: 9200, host: 9200
  config.vm.network :forwarded_port, guest: 9300, host: 9300
  config.vm.network 'public_network', ip: '192.168.0.138'

  config.vm.provider :virtualbox do |v|
    v.name = 'Elasticsearch Vagrant Box'
    box_name  = v.name
    v.customize ['modifyvm', :id, '--cpus', '2', '--memory', '2048']
  end
end
