FROM golang:alpine3.9
WORKDIR /go/src/hargo
COPY . /go/src/hargo

ARG VERSION
ARG HASH
ARG DATE

ENV GO111MODULE=on
ENV GOPROXY=https://proxy.golang.org
RUN go mod download

ENV CGO_ENABLED=0
ENV GOOS=linux

RUN apk add -U --no-cache ca-certificates

RUN go build -ldflags "-s -w -X main.Version=$VERSION -X main.CommitHash=$HASH -X 'main.CompileDate=$DATE'" -o hargo ./cmd/hargo

