FROM mfisherman/texlive-minimal:latest

RUN apk update && apk add --no-cache \
        ncurses openjdk17-jre graphviz xvfb inkscape plantuml

RUN java -version && \
    dot -V && \
    plantuml -version && \
    inkscape --version

ENV GRAPHVIZ_DOT=/usr/bin/dot

WORKDIR /workdir

CMD ["/bin/sh"]
