---
- hosts: all
  connection: local
  gather_facts: yes
  become: yes
  vars:
    filename: test.json
  tasks:
  - name: install web server on centos
    tags: server
    when: "'centos' in ansible_facts['distribution']"
    block:
      - name: debug
        debug:
          msg: pass
  - name: install web server on ubuntu
    tags: server
    when: ansible_facts['distribution'] == 'Debian' or ansible_facts['distribution'] == 'Ubuntu'
    block:
      - name: install package
        apt:
          state: present
          name: apache2
        # alternative: micro-httpd
        tags: apache
      - name: update home page
        copy:
          dest: '/var/www/html/index.html'
          content: this is homepage
      - name: start server
        service:
          enabled: true
          state: started
          name: apache2

  - name: verify installation
    uri:
      url: "http://{{ inventory_hostname }}"
      method: GET
      timeout: 10
      status_code: 200
      return_content: yes
    delegate_to: localhost
    register: result
    tags:
      - always
  - name: print result
    debug:
      var: result.content

