--- 
# based on: https://docs.ansible.com/ansible/latest/dev_guide/developing_modules_general.html
- hosts: localhost
  gather_facts: no
  become: false
  tasks:
    - name: test
      register: result
      diff_module:
        source: 'hello'
        target: 'goodbye'
    - debug: var=result  
