---
modules:
  stub:
    method: GET
    headers:
      Accept: application/json
    url: http://localhost:80/data
    params:
      ts: "{{.Labels.timestamp}}"  # passed from Prometheus target label
    response_format:
      type: json
    metrics:
    - name: stub_metric_value
      path: "{.metric_value}"
#      type: counter
# 0.5.0 does not understand 'counter','gauge' - only untyped
