# NOTE: the ARG appears to be ignored in FROM command. 
# NOTE: this defects the purpose of pinnin
# ARG EXPORTER_VERSION=v1.3.1
# FROM prom/node-exporter:${EXPORTER_VERSION}
FROM prom/node-exporter:v1.3.1
# invalid reference format
EXPOSE 9100
# USER nobody
# USER ROOT
RUN mkdir /tmp/metrics    
COPY  static-metrics.prom /tmp/metrics/

ENTRYPOINT [ "/bin/node_exporter", "--collector.textfile.directory", "/tmp/metrics" ]
