FROM gradle:8.1-jdk11-alpine
WORKDIR /work
ADD buildSrc ./buildSrc/
COPY build.gradle dependencies.gradle versioning.gradle settings.gradle ./
CMD ["gradle", "clean", "build", "printGroovyVersionBuildSrc"]
